#!/usr/bin/env bash
set -euo pipefail

cd /var/www/html

# ---------- Defaults (safe, no DB config required by user) ----------
: "${OB_DB_HOST:=127.0.0.1}"
: "${OB_DB_NAME:=observer}"
: "${OB_DB_USER:=observer}"
: "${OB_DB_PASS:=observer}"
: "${OB_HASH_SALT:=change_me}"
: "${OB_SITE:=http://localhost/}"
: "${OB_EMAIL_FROM:=OpenBroadcaster}"
: "${OB_EMAIL_REPLY:=noreply@example.com}"
: "${OB_MEDIA_BASE:=/var/ob/media}"
: "${OB_MEDIA_UPLOADS:=${OB_MEDIA_BASE}/uploads}"
: "${OB_MEDIA_ARCHIVE:=${OB_MEDIA_BASE}/archive}"
: "${OB_THUMBNAILS:=/var/ob/thumbnails}"
: "${OB_CACHE:=/var/ob/cache}"
: "${OB_ENABLE_CRON_MONITOR:=1}"
: "${OB_RUN_UPDATES_ON_STARTUP:=1}"
: "${OB_FORCE_CONFIG_REGENERATE:=0}"

# Export derived paths for config getenv() usage
export OB_MEDIA="$OB_MEDIA_BASE"
export OB_MEDIA_UPLOADS OB_MEDIA_ARCHIVE OB_THUMBNAILS OB_CACHE

# Ensure writable directories exist
mkdir -p "$OB_MEDIA_BASE" "$OB_MEDIA_UPLOADS" "$OB_MEDIA_ARCHIVE" "$OB_THUMBNAILS" "$OB_CACHE" /var/www/html/assets/uploads
chown -R www-data:www-data /var/ob /var/www/html/assets/uploads || true

# ---------- Embedded MariaDB server ----------
MYSQLD_BIN="$(command -v mariadbd || true)"; [[ -n "$MYSQLD_BIN" ]] || MYSQLD_BIN="$(command -v mysqld || true)"
MYSQL_BIN="$(command -v mariadb || true)"; [[ -n "$MYSQL_BIN" ]] || MYSQL_BIN="$(command -v mysql || true)"
MYSQLADMIN_BIN="$(command -v mariadb-admin || true)"; [[ -n "$MYSQLADMIN_BIN" ]] || MYSQLADMIN_BIN="$(command -v mysqladmin || true)"

# Datadir inside the persisted volume
DB_DATADIR="/var/ob/mysql"
mkdir -p "$DB_DATADIR" /run/mysqld
chown -R mysql:mysql "$DB_DATADIR" /run/mysqld || true

# Initialize datadir if needed
if [[ ! -d "$DB_DATADIR/mysql" ]]; then
  echo "Initializing MariaDB data directory at $DB_DATADIR..."
  mariadb-install-db --user=mysql --datadir="$DB_DATADIR" --skip-test-db >/dev/null
fi

# Start mysqld bound to localhost only
"$MYSQLD_BIN" \
  --user=mysql \
  --datadir="$DB_DATADIR" \
  --bind-address=127.0.0.1 \
  --skip-name-resolve \
  --socket=/run/mysqld/mysqld.sock &
MYSQLD_PID=$!
trap '"$MYSQLADMIN_BIN" --protocol=socket --socket=/run/mysqld/mysqld.sock shutdown || true' TERM INT

# Wait for DB readiness
printf 'Waiting for MariaDB to be ready'
until "$MYSQLADMIN_BIN" --protocol=socket --socket=/run/mysqld/mysqld.sock ping >/dev/null 2>&1; do
  printf '.'
  sleep 1
done
printf '\n'

# Create application database/user and import schema on first run
"$MYSQL_BIN" --protocol=socket --socket=/run/mysqld/mysqld.sock -uroot <<SQL
CREATE DATABASE IF NOT EXISTS \`$OB_DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$OB_DB_USER'@'127.0.0.1' IDENTIFIED BY '$OB_DB_PASS';
CREATE USER IF NOT EXISTS '$OB_DB_USER'@'localhost' IDENTIFIED BY '$OB_DB_PASS';
GRANT ALL PRIVILEGES ON \`$OB_DB_NAME\`.* TO '$OB_DB_USER'@'127.0.0.1';
GRANT ALL PRIVILEGES ON \`$OB_DB_NAME\`.* TO '$OB_DB_USER'@'localhost';
FLUSH PRIVILEGES;
SQL

TABLE_COUNT=$("$MYSQL_BIN" --protocol=socket --socket=/run/mysqld/mysqld.sock -N -s -uroot -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${OB_DB_NAME}'")
if [[ "$TABLE_COUNT" == "0" ]]; then
  echo "Importing initial schema into ${OB_DB_NAME}..."
  # prefer db/dbclean.sql if present, fallback to dbclean.sql legacy name
  if [[ -f db/dbclean.sql ]]; then
    "$MYSQL_BIN" --protocol=socket --socket=/run/mysqld/mysqld.sock -uroot "$OB_DB_NAME" < db/dbclean.sql || true
  elif [[ -f db/clean.sql ]]; then
    "$MYSQL_BIN" --protocol=socket --socket=/run/mysqld/mysqld.sock -uroot "$OB_DB_NAME" < db/clean.sql || true
  fi
fi

# ---------- Generate config.php (from env) ----------
if [[ ! -f config.php || "${OB_FORCE_CONFIG_REGENERATE}" == "1" ]]; then
  echo "Generating config.php from environment..."
  cat > config.php <<'PHP'
<?php
// Auto-generated by docker-entrypoint.sh

define('OB_DB_USER', getenv('OB_DB_USER') ?: 'observer');
define('OB_DB_PASS', getenv('OB_DB_PASS') ?: 'observer');
define('OB_DB_HOST', getenv('OB_DB_HOST') ?: '127.0.0.1');
define('OB_DB_NAME', getenv('OB_DB_NAME') ?: 'observer');

define('OB_HASH_SALT', getenv('OB_HASH_SALT') ?: 'change_me');

define('OB_MEDIA', getenv('OB_MEDIA') ?: '/var/ob/media');
define('OB_MEDIA_UPLOADS', getenv('OB_MEDIA_UPLOADS') ?: getenv('OB_MEDIA').'/uploads');
define('OB_MEDIA_ARCHIVE', getenv('OB_MEDIA_ARCHIVE') ?: getenv('OB_MEDIA').'/archive');

define('OB_THUMBNAILS', getenv('OB_THUMBNAILS') ?: '/var/ob/thumbnails');
define('OB_CACHE', getenv('OB_CACHE') ?: '/var/ob/cache');

define('OB_SITE', rtrim(getenv('OB_SITE') ?: 'http://localhost/', '/').'/');

define('OB_EMAIL_REPLY', getenv('OB_EMAIL_REPLY') ?: 'noreply@example.com');
define('OB_EMAIL_FROM', getenv('OB_EMAIL_FROM') ?: 'OpenBroadcaster');
PHP
  chown www-data:www-data config.php || true
fi

# ---------- Optional: run DB updates, start cron monitor ----------
if [[ "$OB_RUN_UPDATES_ON_STARTUP" == "1" ]]; then
  echo "Running OB updates..."
  chmod +x tools/cli/ob || true
  tools/cli/ob updates run all || true
fi

if [[ "$OB_ENABLE_CRON_MONITOR" == "1" ]]; then
  echo "Starting OB cron monitor in the background..."
  chmod +x tools/cli/ob || true
  tools/cli/ob cron monitor &
  CRON_PID=$!
  trap '"$MYSQLADMIN_BIN" --protocol=socket --socket=/run/mysqld/mysqld.sock shutdown || true; kill -TERM ${CRON_PID} 2>/dev/null || true' TERM INT
fi

# ---------- Hand off to Apache ----------
exec "$@"
